credentials: &credentials
  encoding: utf8
  adapter: postgresql
  username: newsletter
  password: newsletter_pass
  host: localhost
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *credentials 
  database: newsletter_development
 
test:
  <<: *credentials 
  database: newsletter_test
 
production:
  <<: *credentials 
  database: newsletter
